"""Tests for LicenseSigner and cross-library Ed25519 verification.

Verifies that the server's cryptography-based LicenseSigner generates
Ed25519 signatures that are 100% verified by the client's PyNaCl verifier.
"""

from __future__ import annotations

import base64
from unittest.mock import MagicMock
import pytest
from cryptography.hazmat.primitives.asymmetric import ed25519
from cryptography.hazmat.primitives import serialization

from license_server.canonical import canonical_payload
from license_server.errors import SigningError
from license_server.keyvault import AzureKeyVaultClient
from license_server.signer import LicenseSigner
from backend.app.licensing.verifier import verify_signature
from backend.app.licensing.errors import LicenseSignatureError


@pytest.fixture
def keypair():
    """Generate an ephemeral Ed25519 keypair for test execution."""
    private_key = ed25519.Ed25519PrivateKey.generate()
    private_bytes = private_key.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public_bytes = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    return {
        "private_bytes": private_bytes,
        "private_b64": base64.b64encode(private_bytes).decode("ascii"),
        "public_bytes": public_bytes,
        "public_b64": base64.b64encode(public_bytes).decode("ascii"),
    }


@pytest.fixture
def mock_kv_client(keypair):
    """Mock Key Vault client returning the base64-encoded private key."""
    client = MagicMock(spec=AzureKeyVaultClient)
    client.get_secret.return_value = keypair["private_b64"]
    return client


def test_signer_generates_valid_signature_for_client_verifier(mock_kv_client, keypair):
    """Verify that client verify_signature accepts the signature generated by LicenseSigner."""
    signer = LicenseSigner(key_vault_client=mock_kv_client, secret_name="test-signing-key")

    payload = {
        "license_id": "LIC-PROD-2026",
        "product": "alteryx-etl",
        "status": "active",
        "client_instance_id": "client-123",
        "request_id": "req-456",
    }
    canon_bytes = canonical_payload(payload)

    # Server signs
    sig_b64 = signer.sign(canon_bytes)
    assert isinstance(sig_b64, str)
    assert len(base64.b64decode(sig_b64)) == 64

    # Client verifies with PyNaCl
    verified = verify_signature(
        payload_dict=payload,
        signature_b64=sig_b64,
        public_key_b64=keypair["public_b64"],
    )
    assert verified is True


def test_tampered_payload_fails_client_verification(mock_kv_client, keypair):
    """Any modification to the payload must fail client signature verification."""
    signer = LicenseSigner(key_vault_client=mock_kv_client, secret_name="test-signing-key")

    original_payload = {
        "license_id": "LIC-PROD-2026",
        "status": "active",
    }
    canon_bytes = canonical_payload(original_payload)
    sig_b64 = signer.sign(canon_bytes)

    # Tampered payload
    tampered_payload = {
        "license_id": "LIC-PROD-2026",
        "status": "revoked",  # tampered field
    }

    with pytest.raises(LicenseSignatureError):
        verify_signature(
            payload_dict=tampered_payload,
            signature_b64=sig_b64,
            public_key_b64=keypair["public_b64"],
        )


def test_tampered_signature_fails_client_verification(mock_kv_client, keypair):
    """Corrupt signature must fail verification."""
    signer = LicenseSigner(key_vault_client=mock_kv_client, secret_name="test-signing-key")

    payload = {"license_id": "LIC-001"}
    sig_b64 = signer.sign(canonical_payload(payload))

    sig_bytes = bytearray(base64.b64decode(sig_b64))
    sig_bytes[0] ^= 0xFF  # Flip bits
    corrupt_sig_b64 = base64.b64encode(sig_bytes).decode("ascii")

    with pytest.raises(LicenseSignatureError):
        verify_signature(
            payload_dict=payload,
            signature_b64=corrupt_sig_b64,
            public_key_b64=keypair["public_b64"],
        )


def test_signer_caching_and_error_handling(keypair):
    """Test that key vault is accessed only once and invalid key data raises SigningError."""
    kv_client = MagicMock(spec=AzureKeyVaultClient)
    kv_client.get_secret.return_value = "invalid-base64-not-32-bytes"

    signer = LicenseSigner(key_vault_client=kv_client, secret_name="bad-key")
    with pytest.raises(SigningError):
        signer.sign(b"test data")
