"""Python traceability models.

Records line-level source mappings from Alteryx tools to generated Python code,
plus deterministic "why" explanations for each translated operation.
"""

from __future__ import annotations

from dataclasses import dataclass, field as dc_field


@dataclass
class ToolExplanation:
    """Deterministic explanation for why a particular Python operation
    was selected to represent an Alteryx tool.

    Generated by translator metadata — never by an LLM.

    Attributes:
        what_alteryx_does: Plain-English description of the Alteryx tool's function.
        what_pandas_does: The pandas/Python operation used.
        why_selected: Why this particular operation was chosen.
        libraries: Libraries required by the generated code for this tool.
    """
    what_alteryx_does: str
    what_pandas_does: str
    why_selected: str
    libraries: list[str] = dc_field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "what_alteryx_does": self.what_alteryx_does,
            "what_pandas_does": self.what_pandas_does,
            "why_selected": self.why_selected,
            "libraries": self.libraries,
        }


@dataclass
class PythonTraceEntry:
    """Maps a single Alteryx tool to its generated Python code lines.

    Attributes:
        tool_id: The Alteryx tool ID.
        tool_type: The Alteryx tool type string.
        tool_name: Display name of the tool.
        start_line: First line of generated code (1-indexed, inclusive).
        end_line: Last line of generated code (1-indexed, inclusive).
        description: Human-readable description of the transformation.
        pandas_op: The pandas operation used (e.g. 'pd.read_csv', 'boolean indexing').
        reason: Why this operation was selected.
        libraries: Libraries required for this specific tool's code.
    """
    tool_id: int
    tool_type: str
    tool_name: str
    start_line: int
    end_line: int
    description: str
    pandas_op: str
    reason: str
    libraries: list[str] = dc_field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "tool_id": self.tool_id,
            "tool_type": self.tool_type,
            "tool_name": self.tool_name,
            "start_line": self.start_line,
            "end_line": self.end_line,
            "description": self.description,
            "pandas_op": self.pandas_op,
            "reason": self.reason,
            "libraries": self.libraries,
        }


@dataclass
class PythonTraceMap:
    """Complete traceability map for a generated Python file.

    Attributes:
        entries: Ordered list of trace entries, one per tool.
        total_lines: Total number of lines in the generated Python file.
    """
    entries: list[PythonTraceEntry] = dc_field(default_factory=list)
    total_lines: int = 0

    def to_dict(self) -> dict:
        return {
            "entries": [e.to_dict() for e in self.entries],
            "total_lines": self.total_lines,
        }

    def get_entry(self, tool_id: int) -> PythonTraceEntry | None:
        """Look up the trace entry for a given tool ID."""
        for entry in self.entries:
            if entry.tool_id == tool_id:
                return entry
        return None
