"""Developer category tool definitions (Tools 44-58)."""

from __future__ import annotations

from awa.model.diagnostic import SupportLevel
from awa.tools.categories import ToolCategory
from awa.tools.definition import ToolDefinition

DEVELOPER_TOOLS: tuple[ToolDefinition, ...] = (
    # 44. Block Until Done
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.BlockUntilDone.BlockUntilDone",
        display_name="Block Until Done",
        category=ToolCategory.DEVELOPER,
        support_level=SupportLevel.PASS_THROUGH,
        alters_data=False,
        is_blocking=True,
        is_macro=False,
        has_python_translation=False,
        translator_name="PassThroughTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output1", "Output2", "Output3"),
        aliases=("BlockUntilDone",),
        description="Controls execution sequence by holding downstream branches until preceding branches complete.",
        visual_category="developer",
    ),
    # 45. Detour
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.Detour.Detour",
        display_name="Detour",
        category=ToolCategory.DEVELOPER,
        support_level=SupportLevel.PARTIAL,
        alters_data=False,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Left", "Right"),
        aliases=("Detour",),
        description="Bypasses downstream workflow logic by routing data to either the left or right branch.",
        visual_category="developer",
    ),
    # 46. Detour End
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.DetourEnd.DetourEnd",
        display_name="Detour End",
        category=ToolCategory.DEVELOPER,
        support_level=SupportLevel.PASS_THROUGH,
        alters_data=False,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name="PassThroughTranslator",
        parser_name=None,
        input_anchors=("Left", "Right"),
        output_anchors=("Output",),
        aliases=("DetourEnd",),
        description="Merges separated branches from a preceding Detour tool back into a single unified stream.",
        visual_category="developer",
    ),
    # 47. Download
    ToolDefinition(
        xml_name="AlteryxConnectorGui.Download.Download",
        display_name="Download",
        category=ToolCategory.DEVELOPER,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Download",),
        description="Retrieves data or files from web APIs and URLs via HTTP GET/POST requests.",
        visual_category="developer",
    ),
    # 48. Dynamic Input
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.DynamicInput.DynamicInput",
        display_name="Dynamic Input",
        category=ToolCategory.DEVELOPER,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("DynamicInput",),
        description="Dynamically alters queries, database paths, or input files based on incoming record values.",
        visual_category="developer",
    ),
    # 49. Dynamic Rename
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.DynamicRename.DynamicRename",
        display_name="Dynamic Rename",
        category=ToolCategory.DEVELOPER,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="DynamicRenameTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("DynamicRename",),
        description="Dynamically renames columns using formulas, metadata prefixes/suffixes, or secondary lookup tables.",
        visual_category="developer",
    ),
    # 50. Dynamic Replace
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.DynamicReplace.DynamicReplace",
        display_name="Dynamic Replace",
        category=ToolCategory.DEVELOPER,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Targets", "Expressions"),
        output_anchors=("Output", "Errors"),
        aliases=("DynamicReplace",),
        description="Dynamically updates field values based on conditions defined in a secondary expression table.",
        visual_category="developer",
    ),
    # 51. Dynamic Select
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.DynamicSelect.DynamicSelect",
        display_name="Dynamic Select",
        category=ToolCategory.DEVELOPER,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="DynamicSelectTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("DynamicSelect",),
        description="Selects or filters columns dynamically using boolean formulas or data type conditions.",
        visual_category="developer",
    ),
    # 52. Field Info
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.FieldInfo.FieldInfo",
        display_name="Field Info",
        category=ToolCategory.DEVELOPER,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="FieldInfoTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("FieldInfo",),
        description="Extracts column metadata (names, types, sizes, descriptions) into a tabular output stream.",
        visual_category="developer",
    ),
    # 53. JSON Build
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.JSONBuild.JSONBuild",
        display_name="JSON Build",
        category=ToolCategory.DEVELOPER,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=True,
        is_macro=False,
        has_python_translation=True,
        translator_name="JSONBuildTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("JSONBuild", "JsonBuild"),
        description="Constructs hierarchical JSON text strings from key/value pair records.",
        visual_category="developer",
    ),
    # 54. JSON Parse
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.JSONParse.JSONParse",
        display_name="JSON Parse",
        category=ToolCategory.DEVELOPER,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="JSONParseTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("JSONParse", "JsonParse"),
        description="Parses structured JSON strings into discrete key/value columns and arrays.",
        visual_category="developer",
    ),
    # 55. Message
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.Message.Message",
        display_name="Message",
        category=ToolCategory.DEVELOPER,
        support_level=SupportLevel.PASS_THROUGH,
        alters_data=False,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name="PassThroughTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Message",),
        description="Emits informational messages, warnings, or errors to the execution log when conditions are met.",
        visual_category="developer",
    ),
    # 56. Python
    ToolDefinition(
        xml_name="Python",
        display_name="Python",
        category=ToolCategory.DEVELOPER,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("1", "2", "3"),
        output_anchors=("1", "2", "3"),
        aliases=("AlteryxBasePluginsGui.Python.Python", "JupyterCode"),
        description="Executes arbitrary embedded Python code within an interactive Jupyter notebook container.",
        visual_category="developer",
    ),
    # 57. R
    ToolDefinition(
        xml_name="AlteryxRPluginGui.R.R",
        display_name="R",
        category=ToolCategory.DEVELOPER,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("1", "2", "3"),
        output_anchors=("1", "2", "3"),
        aliases=("R", "AlteryxRPluginEngine.R"),
        description="Executes embedded R statistical scripting code on incoming data streams.",
        visual_category="developer",
    ),
    # 58. Run Command
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.RunCommand.RunCommand",
        display_name="Run Command",
        category=ToolCategory.DEVELOPER,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=True,
        is_blocking=True,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("RunCommand",),
        description="Executes external operating system command-line programs, batch files, or executables.",
        visual_category="developer",
    ),
)
