"""Join category tool definitions (Tools 26-32)."""

from __future__ import annotations

from awa.model.diagnostic import SupportLevel
from awa.tools.categories import ToolCategory
from awa.tools.definition import ToolDefinition

JOIN_TOOLS: tuple[ToolDefinition, ...] = (
    # 26. Append Fields
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.AppendFields.AppendFields",
        display_name="Append Fields",
        category=ToolCategory.JOIN,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="AppendFieldsTranslator",
        parser_name=None,
        input_anchors=("Targets", "Source"),
        output_anchors=("Output",),
        aliases=("AppendFields",),
        description="Performs a Cartesian (cross) product between target records and source records.",
        visual_category="join",
    ),
    # 27. Find Replace
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.FindReplace.FindReplace",
        display_name="Find Replace",
        category=ToolCategory.JOIN,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="FindReplaceTranslator",
        parser_name=None,
        input_anchors=("Targets", "Source"),
        output_anchors=("Output",),
        aliases=("FindReplace",),
        description="Searches for substrings or exact matches in a target table and replaces or appends values from a reference table.",
        visual_category="join",
    ),
    # 28. Fuzzy Match
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.FuzzyMatch.FuzzyMatch",
        display_name="Fuzzy Match",
        category=ToolCategory.JOIN,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=True,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("FuzzyMatch",),
        description="Identifies non-exact duplicate and matching records using phonetic and edit-distance matching algorithms.",
        visual_category="join",
    ),
    # 29. Join
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.Join.Join",
        display_name="Join",
        category=ToolCategory.JOIN,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="JoinTranslator",
        parser_name="extract_join_config",
        input_anchors=("Left", "Right"),
        output_anchors=("Left", "Join", "Right"),
        aliases=("Join",),
        description="Combines two data streams based on common key columns or record position, outputting matched, left-unmatched, and right-unmatched streams.",
        visual_category="join",
    ),
    # 30. Join Multiple
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.JoinMultiple.JoinMultiple",
        display_name="Join Multiple",
        category=ToolCategory.JOIN,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="JoinMultipleTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("JoinMultiple",),
        description="Performs an n-way relational join across three or more data inputs simultaneously.",
        visual_category="join",
    ),
    # 31. Make Group
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.MakeGroup.MakeGroup",
        display_name="Make Group",
        category=ToolCategory.JOIN,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=True,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("MakeGroup",),
        description="Creates connected component groups based on pair-wise record relationships.",
        visual_category="join",
    ),
    # 32. Union
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.Union.Union",
        display_name="Union",
        category=ToolCategory.JOIN,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="UnionTranslator",
        parser_name="extract_union_config",
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Union",),
        description="Concatenates multiple data streams vertically by column name or positional order.",
        visual_category="join",
    ),
)
