"""Reporting category tool definitions (Tools 61-70)."""

from __future__ import annotations

from awa.model.diagnostic import SupportLevel
from awa.tools.categories import ToolCategory
from awa.tools.definition import ToolDefinition

REPORTING_TOOLS: tuple[ToolDefinition, ...] = (
    # 61. Email
    ToolDefinition(
        xml_name="AlteryxReportPluginsGui.Email.Email",
        display_name="Email",
        category=ToolCategory.REPORTING,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=False,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=(),
        aliases=("Email",),
        description="Sends emails with attached report snippets, tables, or output files via SMTP.",
        visual_category="reporting",
    ),
    # 62. Layout
    ToolDefinition(
        xml_name="AlteryxReportPluginsGui.Layout.Layout",
        display_name="Layout",
        category=ToolCategory.REPORTING,
        support_level=SupportLevel.DOCUMENTATION_ONLY,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Layout",),
        description="Combines multiple reporting elements (charts, tables, text) into a formatted horizontal/vertical layout snippet.",
        visual_category="reporting",
    ),
    # 63. Render
    ToolDefinition(
        xml_name="AlteryxReportPluginsGui.Render.Render",
        display_name="Render",
        category=ToolCategory.REPORTING,
        support_level=SupportLevel.DOCUMENTATION_ONLY,
        alters_data=False,
        is_blocking=True,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=(),
        aliases=("Render",),
        description="Transforms reporting snippets into final document formats (PDF, DOCX, HTML, PPTX, PNG).",
        visual_category="reporting",
    ),
    # 64. Report Footer
    ToolDefinition(
        xml_name="ReportFooter.yxmc",
        display_name="Report Footer",
        category=ToolCategory.REPORTING,
        support_level=SupportLevel.DOCUMENTATION_ONLY,
        alters_data=True,
        is_blocking=False,
        is_macro=True,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("AlteryxReportPluginsGui.ReportFooter.ReportFooter", "ReportFooter"),
        description="Appends standardized footer snippets, copyright text, and page numbering to report layouts.",
        visual_category="reporting",
    ),
    # 65. Report Header
    ToolDefinition(
        xml_name="ReportHeader.yxmc",
        display_name="Report Header",
        category=ToolCategory.REPORTING,
        support_level=SupportLevel.DOCUMENTATION_ONLY,
        alters_data=True,
        is_blocking=False,
        is_macro=True,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("AlteryxReportPluginsGui.ReportHeader.ReportHeader", "ReportHeader"),
        description="Appends standardized header snippets, title, and organization branding logos to reports.",
        visual_category="reporting",
    ),
    # 66. Report Map
    ToolDefinition(
        xml_name="AlteryxReportPluginsGui.ReportMap.ReportMap",
        display_name="Report Map",
        category=ToolCategory.REPORTING,
        support_level=SupportLevel.DOCUMENTATION_ONLY,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("ReportMap",),
        description="Renders spatial polygons, points, lines, and heatmaps into cartographic report image snippets.",
        visual_category="reporting",
    ),
    # 67. Report Text
    ToolDefinition(
        xml_name="AlteryxReportPluginsGui.ReportText.ReportText",
        display_name="Report Text",
        category=ToolCategory.REPORTING,
        support_level=SupportLevel.DOCUMENTATION_ONLY,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("ReportText",),
        description="Generates rich formatted text snippets with dynamic field replacement values for inclusion in reports.",
        visual_category="reporting",
    ),
    # 68. Table
    ToolDefinition(
        xml_name="AlteryxReportPluginsGui.Table.Table",
        display_name="Table",
        category=ToolCategory.REPORTING,
        support_level=SupportLevel.DOCUMENTATION_ONLY,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Table",),
        description="Formats tabular datasets into styled report presentation table snippets with custom rules.",
        visual_category="reporting",
    ),
    # 69. Interactive Chart
    ToolDefinition(
        xml_name="AlteryxReportPluginsGui.InteractiveChart.InteractiveChart",
        display_name="Interactive Chart",
        category=ToolCategory.REPORTING,
        support_level=SupportLevel.DOCUMENTATION_ONLY,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("InteractiveChart",),
        description="Generates interactive Plotly/D3 based chart visualizations from workflow records.",
        visual_category="reporting",
    ),
    # 70. Image
    ToolDefinition(
        xml_name="AlteryxReportPluginsGui.Image.Image",
        display_name="Image",
        category=ToolCategory.REPORTING,
        support_level=SupportLevel.DOCUMENTATION_ONLY,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Image",),
        description="Embeds raster or vector graphics and images into reporting layouts.",
        visual_category="reporting",
    ),
)
