"""Spatial category tool definitions (Tools 71-84)."""

from __future__ import annotations

from awa.model.diagnostic import SupportLevel
from awa.tools.categories import ToolCategory
from awa.tools.definition import ToolDefinition

SPATIAL_TOOLS: tuple[ToolDefinition, ...] = (
    # 71. Buffer
    ToolDefinition(
        xml_name="AlteryxSpatialPluginsGui.Buffer.Buffer",
        display_name="Buffer",
        category=ToolCategory.SPATIAL,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Buffer",),
        description="Expands or contracts the boundary of any polygon or polyline spatial object by a specified radius.",
        visual_category="spatial",
    ),
    # 72. Create Points
    ToolDefinition(
        xml_name="AlteryxSpatialPluginsGui.CreatePoints.CreatePoints",
        display_name="Create Points",
        category=ToolCategory.SPATIAL,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("CreatePoints",),
        description="Creates spatial point objects from numerical latitude and longitude coordinate columns.",
        visual_category="spatial",
    ),
    # 73. Distance
    ToolDefinition(
        xml_name="AlteryxSpatialPluginsGui.Distance.Distance",
        display_name="Distance",
        category=ToolCategory.SPATIAL,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Distance",),
        description="Calculates point-to-point, point-to-edge, or driving distances between spatial objects.",
        visual_category="spatial",
    ),
    # 74. Find Nearest
    ToolDefinition(
        xml_name="AlteryxSpatialPluginsGui.FindNearest.FindNearest",
        display_name="Find Nearest",
        category=ToolCategory.SPATIAL,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=True,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Targets", "Universe"),
        output_anchors=("Matched", "Unmatched"),
        aliases=("FindNearest",),
        description="Identifies the nearest spatial objects in a universe dataset relative to a target dataset.",
        visual_category="spatial",
    ),
    # 75. Generalize
    ToolDefinition(
        xml_name="AlteryxSpatialPluginsGui.Generalize.Generalize",
        display_name="Generalize",
        category=ToolCategory.SPATIAL,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Generalize",),
        description="Simplifies spatial polylines and polygons by reducing vertex count within a specified tolerance.",
        visual_category="spatial",
    ),
    # 76. Heat Map
    ToolDefinition(
        xml_name="HeatMap.yxmc",
        display_name="Heat Map",
        category=ToolCategory.SPATIAL,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=True,
        is_macro=True,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("AlteryxSpatialPluginsGui.HeatMap.HeatMap", "HeatMap"),
        description="Generates continuous density heat map polygons based on point clustering and intensity weights.",
        visual_category="spatial",
    ),
    # 77. Make Grid
    ToolDefinition(
        xml_name="AlteryxSpatialPluginsGui.MakeGrid.MakeGrid",
        display_name="Make Grid",
        category=ToolCategory.SPATIAL,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("MakeGrid",),
        description="Creates a regular hexagonal or rectangular spatial polygon grid overlay across a bounding area.",
        visual_category="spatial",
    ),
    # 78. Poly-Build
    ToolDefinition(
        xml_name="AlteryxSpatialPluginsGui.PolyBuild.PolyBuild",
        display_name="Poly-Build",
        category=ToolCategory.SPATIAL,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=True,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("PolyBuild",),
        description="Transforms an ordered sequence of spatial points into convex hulls, polygons, or polylines.",
        visual_category="spatial",
    ),
    # 79. Poly-Split
    ToolDefinition(
        xml_name="AlteryxSpatialPluginsGui.PolySplit.PolySplit",
        display_name="Poly-Split",
        category=ToolCategory.SPATIAL,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("PolySplit",),
        description="Deconstructs polygon and polyline spatial objects into component points, segments, or rings.",
        visual_category="spatial",
    ),
    # 80. Smooth
    ToolDefinition(
        xml_name="AlteryxSpatialPluginsGui.Smooth.Smooth",
        display_name="Smooth",
        category=ToolCategory.SPATIAL,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Smooth",),
        description="Rounds the sharp corners of polygon and polyline spatial objects using spline curve algorithms.",
        visual_category="spatial",
    ),
    # 81. Spatial Info
    ToolDefinition(
        xml_name="AlteryxSpatialPluginsGui.SpatialInfo.SpatialInfo",
        display_name="Spatial Info",
        category=ToolCategory.SPATIAL,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("SpatialInfo",),
        description="Extracts spatial metadata (area, length, centroid coordinates, bounding box) from spatial objects.",
        visual_category="spatial",
    ),
    # 82. Spatial Match
    ToolDefinition(
        xml_name="AlteryxSpatialPluginsGui.SpatialMatch.SpatialMatch",
        display_name="Spatial Match",
        category=ToolCategory.SPATIAL,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=True,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Targets", "Universe"),
        output_anchors=("Matched", "Unmatched"),
        aliases=("SpatialMatch",),
        description="Establishes spatial relationships (intersects, contains, touches, overlaps) between two spatial datasets.",
        visual_category="spatial",
    ),
    # 83. Spatial Process
    ToolDefinition(
        xml_name="AlteryxSpatialPluginsGui.SpatialProcess.SpatialProcess",
        display_name="Spatial Process",
        category=ToolCategory.SPATIAL,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("SpatialProcess",),
        description="Performs geometric boolean operations (combine, cut, intersect, symmetric difference) between spatial objects.",
        visual_category="spatial",
    ),
    # 84. Trade Area
    ToolDefinition(
        xml_name="AlteryxSpatialPluginsGui.TradeArea.TradeArea",
        display_name="Trade Area",
        category=ToolCategory.SPATIAL,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("TradeArea",),
        description="Creates circular or drive-time catchment areas around spatial point locations.",
        visual_category="spatial",
    ),
)
