"""Transform category tool definitions (Tools 37-43)."""

from __future__ import annotations

from awa.model.diagnostic import SupportLevel
from awa.tools.categories import ToolCategory
from awa.tools.definition import ToolDefinition

TRANSFORM_TOOLS: tuple[ToolDefinition, ...] = (
    # 37. Arrange
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.Arrange.Arrange",
        display_name="Arrange",
        category=ToolCategory.TRANSFORM,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="ArrangeTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Arrange",),
        description="Manually transposes, groups, and arranges column data into standardized output tables.",
        visual_category="reshape",
    ),
    # 38. Count Records
    ToolDefinition(
        xml_name="CountRecords.yxmc",
        display_name="Count Records",
        category=ToolCategory.TRANSFORM,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=True,
        is_macro=True,
        has_python_translation=True,
        translator_name="CountRecordsTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("AlteryxBasePluginsGui.CountRecords.CountRecords", "CountRecords"),
        description="Returns a single row with the exact count of records passing through the stream.",
        visual_category="aggregate",
    ),
    # 39. Cross Tab
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.CrossTab.CrossTab",
        display_name="Cross Tab",
        category=ToolCategory.TRANSFORM,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=True,
        is_macro=False,
        has_python_translation=True,
        translator_name="CrossTabTranslator",
        parser_name="extract_cross_tab_config",
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("CrossTab",),
        description="Pivots vertical tabular data horizontally into a cross-tabulated matrix.",
        visual_category="reshape",
    ),
    # 40. Make Columns
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.MakeColumns.MakeColumns",
        display_name="Make Columns",
        category=ToolCategory.TRANSFORM,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=True,
        is_macro=False,
        has_python_translation=True,
        translator_name="MakeColumnsTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("MakeColumns",),
        description="Arranges rows into multiple columns arranged either horizontally or vertically.",
        visual_category="reshape",
    ),
    # 41. Running Total
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.RunningTotal.RunningTotal",
        display_name="Running Total",
        category=ToolCategory.TRANSFORM,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="RunningTotalTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("RunningTotal",),
        description="Calculates cumulative running totals over rows, optionally segmented by grouping fields.",
        visual_category="aggregate",
    ),
    # 42. Summarize
    ToolDefinition(
        xml_name="AlteryxSpatialPluginsGui.Summarize.Summarize",
        display_name="Summarize",
        category=ToolCategory.TRANSFORM,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=True,
        is_macro=False,
        has_python_translation=True,
        translator_name="SummarizeTranslator",
        parser_name="extract_summarize_config",
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Summarize", "AlteryxBasePluginsGui.Summarize.Summarize"),
        description="Aggregates and summarizes data (Group By, Sum, Count, Min, Max, Avg, First, Last, String Concat).",
        visual_category="summarize",
    ),
    # 43. Transpose
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.Transpose.Transpose",
        display_name="Transpose",
        category=ToolCategory.TRANSFORM,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="TransposeTranslator",
        parser_name="extract_transpose_config",
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Transpose",),
        description="Pivots horizontal columns vertically into Name/Value pairs preserving specified Key columns.",
        visual_category="reshape",
    ),
)
