"""Connectors category tool definitions (Tools 92-100)."""

from __future__ import annotations

from awa.model.diagnostic import SupportLevel
from awa.tools.categories import ToolCategory
from awa.tools.definition import ToolDefinition

CONNECTOR_TOOLS: tuple[ToolDefinition, ...] = (
    # 92. Amazon S3 Download
    ToolDefinition(
        xml_name="AmazonS3Download.yxmc",
        display_name="Amazon S3 Download",
        category=ToolCategory.CONNECTORS,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=True,
        is_blocking=False,
        is_macro=True,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=(),
        output_anchors=("Output",),
        aliases=("AlteryxConnectorGui.AmazonS3Download.AmazonS3Download", "AmazonS3Download"),
        description="Retrieves and reads files stored in Amazon Web Services Simple Storage Service (S3) buckets.",
        visual_category="connector",
    ),
    # 93. Amazon S3 Upload
    ToolDefinition(
        xml_name="AmazonS3Upload.yxmc",
        display_name="Amazon S3 Upload",
        category=ToolCategory.CONNECTORS,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=False,
        is_blocking=False,
        is_macro=True,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=(),
        aliases=("AlteryxConnectorGui.AmazonS3Upload.AmazonS3Upload", "AmazonS3Upload"),
        description="Uploads workflow records and data files to an Amazon S3 cloud bucket destination.",
        visual_category="connector",
    ),
    # 94. SharePoint Files Input
    ToolDefinition(
        xml_name="SharePointFilesInput.yxmc",
        display_name="SharePoint Files Input",
        category=ToolCategory.CONNECTORS,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=True,
        is_blocking=False,
        is_macro=True,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=(),
        output_anchors=("Output",),
        aliases=("AlteryxConnectorGui.SharePointFilesInput.SharePointFilesInput", "SharePointFilesInput"),
        description="Downloads and reads Excel, CSV, or XML data files from Microsoft SharePoint document libraries.",
        visual_category="connector",
    ),
    # 95. SharePoint Files Output
    ToolDefinition(
        xml_name="SharePointFilesOutput.yxmc",
        display_name="SharePoint Files Output",
        category=ToolCategory.CONNECTORS,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=False,
        is_blocking=False,
        is_macro=True,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=(),
        aliases=("AlteryxConnectorGui.SharePointFilesOutput.SharePointFilesOutput", "SharePointFilesOutput"),
        description="Writes and uploads dataset files to a target Microsoft SharePoint document library.",
        visual_category="connector",
    ),
    # 96. Salesforce Input
    ToolDefinition(
        xml_name="SalesforceInput.yxmc",
        display_name="Salesforce Input",
        category=ToolCategory.CONNECTORS,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=True,
        is_blocking=False,
        is_macro=True,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=(),
        output_anchors=("Output",),
        aliases=("AlteryxConnectorGui.SalesforceInput.SalesforceInput", "SalesforceInput"),
        description="Queries and extracts tables and object records from Salesforce CRM via SOQL API.",
        visual_category="connector",
    ),
    # 97. Salesforce Output (New)
    ToolDefinition(
        xml_name="SalesforceOutput.yxmc",
        display_name="Salesforce Output (New)",
        category=ToolCategory.CONNECTORS,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=False,
        is_blocking=False,
        is_macro=True,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=(),
        aliases=("AlteryxConnectorGui.SalesforceOutput.SalesforceOutput", "SalesforceOutput"),
        description="Inserts, updates, or upserts workflow records into Salesforce database objects via API.",
        visual_category="connector",
    ),
    # 98. Tableau Output
    ToolDefinition(
        xml_name="TableauOutput.yxmc",
        display_name="Tableau Output",
        category=ToolCategory.CONNECTORS,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=False,
        is_blocking=False,
        is_macro=True,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=(),
        aliases=("AlteryxConnectorGui.TableauOutput.TableauOutput", "TableauOutput", "PublishToTableauServer.yxmc"),
        description="Publishes data extracts (.hyper) directly to Tableau Server or Tableau Cloud sites.",
        visual_category="connector",
    ),
    # 99. MongoDB Input
    ToolDefinition(
        xml_name="AlteryxConnectorGui.MongoInput.MongoInput",
        display_name="MongoDB Input",
        category=ToolCategory.CONNECTORS,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=(),
        output_anchors=("Output",),
        aliases=("MongoInput", "MongoDBInput"),
        description="Queries documents from MongoDB NoSQL database collections and flattens into tabular records.",
        visual_category="connector",
    ),
    # 100. MongoDB Output
    ToolDefinition(
        xml_name="AlteryxConnectorGui.MongoOutput.MongoOutput",
        display_name="MongoDB Output",
        category=ToolCategory.CONNECTORS,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=False,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=(),
        aliases=("MongoOutput", "MongoDBOutput"),
        description="Writes workflow data streams as JSON documents into MongoDB collections.",
        visual_category="connector",
    ),
)
