"""In-Database category tool definitions (Tools 85-91)."""

from __future__ import annotations

from awa.model.diagnostic import SupportLevel
from awa.tools.categories import ToolCategory
from awa.tools.definition import ToolDefinition

IN_DATABASE_TOOLS: tuple[ToolDefinition, ...] = (
    # 85. Connect In-DB
    ToolDefinition(
        xml_name="LockInGui.LockInInput.LockInInput",
        display_name="Connect In-DB",
        category=ToolCategory.IN_DATABASE,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=(),
        output_anchors=("Output",),
        aliases=("LockInInput", "ConnectInDB"),
        description="Establishes an in-database query connection to a relational or cloud warehouse database.",
        visual_category="in_database",
    ),
    # 86. Data Stream In
    ToolDefinition(
        xml_name="LockInGui.LockInStreamIn.LockInStreamIn",
        display_name="Data Stream In",
        category=ToolCategory.IN_DATABASE,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=True,
        is_blocking=True,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("LockInStreamIn", "DataStreamIn"),
        description="Streams in-memory workflow records into a temporary table inside the connected database engine.",
        visual_category="in_database",
    ),
    # 87. Data Stream Out
    ToolDefinition(
        xml_name="LockInGui.LockInStreamOut.LockInStreamOut",
        display_name="Data Stream Out",
        category=ToolCategory.IN_DATABASE,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("LockInStreamOut", "DataStreamOut"),
        description="Executes the accumulated In-DB query pipeline and streams results back into in-memory workflow data.",
        visual_category="in_database",
    ),
    # 88. Filter In-DB
    ToolDefinition(
        xml_name="LockInGui.LockInFilter.LockInFilter",
        display_name="Filter In-DB",
        category=ToolCategory.IN_DATABASE,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=False,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("True", "False"),
        aliases=("LockInFilter", "FilterInDB"),
        description="Applies SQL WHERE filter clauses directly inside the database engine query plan.",
        visual_category="in_database",
    ),
    # 89. Formula In-DB
    ToolDefinition(
        xml_name="LockInGui.LockInFormula.LockInFormula",
        display_name="Formula In-DB",
        category=ToolCategory.IN_DATABASE,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("LockInFormula", "FormulaInDB"),
        description="Applies SQL expressions and column transformations natively within the database query.",
        visual_category="in_database",
    ),
    # 90. Join In-DB
    ToolDefinition(
        xml_name="LockInGui.LockInJoin.LockInJoin",
        display_name="Join In-DB",
        category=ToolCategory.IN_DATABASE,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Left", "Right"),
        output_anchors=("Left", "Join", "Right"),
        aliases=("LockInJoin", "JoinInDB"),
        description="Executes native SQL relational joins between two In-DB database tables or subqueries.",
        visual_category="in_database",
    ),
    # 91. Select In-DB
    ToolDefinition(
        xml_name="LockInGui.LockInSelect.LockInSelect",
        display_name="Select In-DB",
        category=ToolCategory.IN_DATABASE,
        support_level=SupportLevel.EXTERNAL_EXECUTION,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("LockInSelect", "SelectInDB"),
        description="Selects, renames, and typecasts columns inside the database execution plan.",
        visual_category="in_database",
    ),
)
