"""Preparation category tool definitions (Tools 7-25)."""

from __future__ import annotations

from awa.model.diagnostic import SupportLevel
from awa.tools.categories import ToolCategory
from awa.tools.definition import ToolDefinition

PREPARATION_TOOLS: tuple[ToolDefinition, ...] = (
    # 7. Auto Field
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.AutoField.AutoField",
        display_name="Auto Field",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=True,
        is_macro=False,
        has_python_translation=True,
        translator_name="AutoFieldTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("AutoField",),
        description="Automatically optimizes field data types to the smallest possible type based on incoming data values.",
        visual_category="select",
    ),
    # 8. Data Cleanse Pro
    ToolDefinition(
        xml_name="DataCleansePro",
        display_name="Data Cleanse Pro",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=False,
        is_macro=True,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("DataCleansePro.yxmc",),
        description="Enhanced data cleansing tool with advanced text replacement and normalization rules.",
        visual_category="cleansing",
    ),
    # 9. Data Cleansing
    ToolDefinition(
        xml_name="Cleanse.yxmc",
        display_name="Data Cleansing",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=True,
        has_python_translation=True,
        translator_name="DataCleansingTranslator",
        parser_name="extract_data_cleansing_config",
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("DataCleansing", "AlteryxBasePluginsGui.DataCleansing.DataCleansing"),
        description="Cleanses fields by removing null values, leading/trailing whitespace, and modifying text casing.",
        visual_category="cleansing",
    ),
    # 10. Filter
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.Filter.Filter",
        display_name="Filter",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.FULL,
        alters_data=False,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="FilterTranslator",
        parser_name="extract_filter_config",
        input_anchors=("Input",),
        output_anchors=("True", "False"),
        aliases=("Filter",),
        description="Splits incoming data streams into True and False branches based on a boolean expression.",
        visual_category="filter",
    ),
    # 11. Formula
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.Formula.Formula",
        display_name="Formula",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="FormulaTranslator",
        parser_name="extract_formula_config",
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Formula",),
        description="Applies mathematical, string, datetime, and logical expressions to create or update columns.",
        visual_category="formula",
    ),
    # 12. Generate Rows
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.GenerateRows.GenerateRows",
        display_name="Generate Rows",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="GenerateRowsTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("GenerateRows",),
        description="Generates new rows of data using initialization, loop, and termination conditions.",
        visual_category="generate",
    ),
    # 13. Multi-Field Formula
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.MultiFieldFormula.MultiFieldFormula",
        display_name="Multi-Field Formula",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="MultiFieldFormulaTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("MultiFieldFormula",),
        description="Applies a single formula across multiple selected fields simultaneously.",
        visual_category="formula",
    ),
    # 14. Multi-Row Formula
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.MultiRowFormula.MultiRowFormula",
        display_name="Multi-Row Formula",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="MultiRowFormulaTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("MultiRowFormula",),
        description="References preceding or subsequent rows to calculate lag, lead, and running values.",
        visual_category="formula",
    ),
    # 15. Record ID
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.RecordID.RecordID",
        display_name="Record ID",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="RecordIdTranslator",
        parser_name="extract_record_id_config",
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("RecordID", "RecordId"),
        description="Appends a sequential numeric identifier column to incoming records.",
        visual_category="reshape",
    ),
    # 16. Sample
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.Sample.Sample",
        display_name="Sample",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.FULL,
        alters_data=False,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="SampleTranslator",
        parser_name="extract_sample_config",
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Sample",),
        description="Extracts first N, last N, or percentage subsets of records.",
        visual_category="reshape",
    ),
    # 17. Select
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.AlteryxSelect.AlteryxSelect",
        display_name="Select",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="SelectTranslator",
        parser_name="extract_select_config",
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Select", "AlteryxSelect"),
        description="Selects, excludes, renames, and typecasts columns in the data stream.",
        visual_category="select",
    ),
    # 18. Select Records
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.SelectRecords.SelectRecords",
        display_name="Select Records",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.FULL,
        alters_data=False,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="SelectRecordsTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("SelectRecords.yxmc", "SelectRecords"),
        description="Filters data stream by specific record row numbers or ranges.",
        visual_category="select",
    ),
    # 19. Sort
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.Sort.Sort",
        display_name="Sort",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.FULL,
        alters_data=False,
        is_blocking=True,
        is_macro=False,
        has_python_translation=True,
        translator_name="SortTranslator",
        parser_name="extract_sort_config",
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Sort",),
        description="Sorts records ascending or descending based on one or more key columns.",
        visual_category="sort",
    ),
    # 20. Tile
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.Tile.Tile",
        display_name="Tile",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=True,
        is_macro=False,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Tile",),
        description="Assigns a tile number based on equal records, equal intervals, or unique values.",
        visual_category="transform",
    ),
    # 21. Unique
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.Unique.Unique",
        display_name="Unique",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.FULL,
        alters_data=False,
        is_blocking=False,
        is_macro=False,
        has_python_translation=True,
        translator_name="UniqueTranslator",
        parser_name="extract_unique_config",
        input_anchors=("Input",),
        output_anchors=("Unique", "Duplicates"),
        aliases=("Unique",),
        description="Separates unique records from duplicate records based on specified key columns.",
        visual_category="unique",
    ),
    # 22. Rank
    ToolDefinition(
        xml_name="AlteryxBasePluginsGui.Rank.Rank",
        display_name="Rank",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.FULL,
        alters_data=True,
        is_blocking=True,
        is_macro=False,
        has_python_translation=True,
        translator_name="RankTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("Rank.yxmc", "Rank"),
        description="Calculates dense or standard rank positions for numeric or ordinal columns.",
        visual_category="sort",
    ),
    # 23. Random % Sample
    ToolDefinition(
        xml_name="RandomSampleSize.yxmc",
        display_name="Random % Sample",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.FULL,
        alters_data=False,
        is_blocking=False,
        is_macro=True,
        has_python_translation=True,
        translator_name="RandomSampleTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("AlteryxBasePluginsGui.RandomSampleSize.RandomSampleSize", "RandomSampleSize"),
        description="Draws an unbiased pseudo-random percentage sample of rows from the data stream.",
        visual_category="reshape",
    ),
    # 24. Create Samples
    ToolDefinition(
        xml_name="CreateSamples.yxmc",
        display_name="Create Samples",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.FULL,
        alters_data=False,
        is_blocking=False,
        is_macro=True,
        has_python_translation=True,
        translator_name="CreateSamplesTranslator",
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Estimation", "Validation", "Holdout"),
        aliases=("AlteryxBasePluginsGui.CreateSamples.CreateSamples", "CreateSamples"),
        description="Partitions data stream into Estimation, Validation, and Holdout samples for modeling.",
        visual_category="reshape",
    ),
    # 25. Multi-Field Binning
    ToolDefinition(
        xml_name="MultiFieldBinning.yxmc",
        display_name="Multi-Field Binning",
        category=ToolCategory.PREPARATION,
        support_level=SupportLevel.PARTIAL,
        alters_data=True,
        is_blocking=True,
        is_macro=True,
        has_python_translation=False,
        translator_name=None,
        parser_name=None,
        input_anchors=("Input",),
        output_anchors=("Output",),
        aliases=("AlteryxBasePluginsGui.MultiFieldBinning.MultiFieldBinning", "MultiFieldBinning"),
        description="Groups continuous numerical columns into discrete bins or quantiles.",
        visual_category="transform",
    ),
)
