"""Python generator — assembles translations into workflow.py.

Generates only consumed branches per constraint C3.
Provides line-level source mapping and traceability metadata.
"""

from __future__ import annotations

from pathlib import Path

from awa.model.workflow import Workflow
from awa.model.translation import TranslationResult
from awa.model.python_trace import PythonTraceEntry, PythonTraceMap


def generate_python_code(
    workflow: Workflow,
    execution_order: list[int],
    translations: dict[int, TranslationResult],
    consumed: dict[int, set[str]],
) -> tuple[str, PythonTraceMap, list[str]]:
    """Assemble generated Python code and compute line-level traceability map.

    Args:
        workflow: Canonical Workflow IR.
        execution_order: Tool IDs in topological order.
        translations: Translation results keyed by tool_id.
        consumed: Consumed anchors per tool.

    Returns:
        tuple of (generated_python_code_str, PythonTraceMap, required_libraries_list)
    """
    lines: list[str] = []

    # Header
    lines.append('"""')
    lines.append("Auto-generated Python/pandas translation of Alteryx workflow.")
    lines.append(f"Workflow: {workflow.metadata.name}")
    lines.append(f"Version: {workflow.metadata.version}")
    lines.append("")
    lines.append("Generated by AWA (Alteryx Workflow Analyzer).")
    lines.append("This is a deterministic translation — no AI/LLM was used.")
    lines.append('"""')
    lines.append("")

    # Collect all imports
    all_imports: set[str] = set()
    for tid in execution_order:
        if tid in translations:
            all_imports.update(translations[tid].imports)

    # Write imports
    for imp in sorted(all_imports):
        lines.append(imp)
    if all_imports:
        lines.append("")

    # Detect required external libraries strictly from generated imports
    required_libs: set[str] = set()
    for imp in all_imports:
        if "pandas" in imp:
            required_libs.add("pandas")
        elif "numpy" in imp:
            required_libs.add("numpy")
        elif "openpyxl" in imp:
            required_libs.add("openpyxl")
        elif "pyarrow" in imp:
            required_libs.add("pyarrow")
    required_libraries = sorted(required_libs)

    # Track trace entries
    trace_entries: list[PythonTraceEntry] = []

    # Write each tool in execution order
    for tid in execution_order:
        tool = workflow.tools.get(tid)
        tr = translations.get(tid)
        if tool is None or tr is None:
            continue

        # Traceability header
        lines.append("")
        start_line = len(lines) + 1  # 1-indexed, starts at the tool comment header
        lines.append("# " + "=" * 60)
        lines.append(f"# Alteryx Tool #{tool.tool_id}")
        lines.append(f"# Type: {tool.tool_type}")
        if tool.name:
            lines.append(f"# Name: {tool.name}")
        lines.append(f"# Support: {tr.support_level.value}")
        if tr.description:
            lines.append(f"# {tr.description}")
        lines.append("# " + "=" * 60)

        # Add diagnostic notes
        for diag in tr.diagnostics:
            lines.append(f"# {diag.level.value.upper()}: {diag.message}")

        # Code block
        code = tr.python_code
        for code_line in code.split("\n"):
            lines.append(code_line)

        end_line = len(lines)

        # Extract tool libraries
        tool_libs = []
        for imp in tr.imports:
            if "pandas" in imp:
                tool_libs.append("pandas")
            elif "numpy" in imp:
                tool_libs.append("numpy")
            elif "openpyxl" in imp:
                tool_libs.append("openpyxl")
        tool_libs = sorted(set(tool_libs))

        trace_entries.append(
            PythonTraceEntry(
                tool_id=tool.tool_id,
                tool_type=tool.tool_type,
                tool_name=tool.name or tool.tool_type,
                start_line=start_line,
                end_line=end_line,
                description=tr.description or f"{tool.tool_type} operation",
                pandas_op=tr.description or f"pandas {tool.tool_type.lower()}",
                reason=f"Deterministic {tool.tool_type} translation",
                libraries=tool_libs,
            )
        )

    # Ensure single trailing newline
    full_code = "\n".join(lines).rstrip() + "\n"
    # Calculate exact total_lines from final string
    total_lines = len(full_code.splitlines())
    trace_map = PythonTraceMap(entries=trace_entries, total_lines=total_lines)

    return full_code, trace_map, required_libraries


def generate_python(
    workflow: Workflow,
    execution_order: list[int],
    translations: dict[int, TranslationResult],
    consumed: dict[int, set[str]],
    output_path: Path,
) -> tuple[str, PythonTraceMap, list[str]]:
    """Generate workflow.py and write to disk, returning the code, trace map, and libraries."""
    code, trace_map, required_libs = generate_python_code(
        workflow, execution_order, translations, consumed
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(code)

    return code, trace_map, required_libs
